export const mockCompanies = [
  { name: "Apple Inc", symbol: "AAPL" },
  { name: "Microsoft Corporation", symbol: "MSFT" },
  { name: "Tesla Inc", symbol: "TSLA" },
  { name: "Amazon.com Inc", symbol: "AMZN" },
  { name: "Alphabet Inc", symbol: "GOOGL" },
  { name: "Meta Platforms Inc.", symbol: "META" },
  { name: "Nvidia Corporation", symbol: "NVDA" },
  { name: "Netflix Inc", symbol: "NFLX" },
  { name: "Intel Corporation", symbol: "INTC" },
  { name: "Adobe Inc", symbol: "ADBE" },
  { name: "Zoom Video Communications", symbol: "ZM" },
  { name: "PayPal Holdings Inc", symbol: "PYPL" },
  { name: "Salesforce.com Inc", symbol: "CRM" },
  { name: "Qualcomm Inc", symbol: "QCOM" },
  { name: "Broadcom Inc", symbol: "AVGO" },
  { name: "Cisco Systems Inc", symbol: "CSCO" },
  { name: "Uber Technologies Inc", symbol: "UBER" },
  { name: "Shopify Inc", symbol: "SHOP" },
  { name: "Spotify Technology S.A.", symbol: "SPOT" },
  { name: "Block Inc", symbol: "SQ" },
];

export const mockProfile = {
  AAPL: {
    symbol: "AAPL",
    companyName: "Apple Inc.",
    description: "Apple is a technology company...",
    website: "https://www.apple.com",
    image: "https://logo.clearbit.com/apple.com",
    price: 198.23,
    changesPercentage: "+1.65%",
  },
  MSFT: {
    symbol: "MSFT",
    companyName: "Microsoft Corporation",
    description: "Microsoft develops software...",
    website: "https://www.microsoft.com",
    image: "https://logo.clearbit.com/microsoft.com",
    price: 345.61,
    changesPercentage: "+0.85%",
  },
  TSLA: {
    symbol: "TSLA",
    companyName: "Tesla Inc.",
    description: "Tesla makes electric vehicles...",
    website: "https://www.tesla.com",
    image: "https://logo.clearbit.com/tesla.com",
    price: 701.32,
    changesPercentage: "-2.12%",
  },
  AMZN: {
    symbol: "AMZN",
    companyName: "Amazon.com Inc.",
    description: "Amazon is an e-commerce giant...",
    website: "https://www.amazon.com",
    image: "https://logo.clearbit.com/amazon.com",
    price: 132.5,
    changesPercentage: "+0.45%",
  },
  GOOGL: {
    symbol: "GOOGL",
    companyName: "Alphabet Inc.",
    description: "Alphabet is the parent company of Google...",
    website: "https://www.abc.xyz",
    image: "https://logo.clearbit.com/abc.xyz",
    price: 132.12,
    changesPercentage: "-0.25%",
  },
  META: {
    symbol: "META",
    companyName: "Meta Platforms Inc.",
    description: "Meta develops social media platforms...",
    website: "https://about.meta.com",
    image: "https://logo.clearbit.com/meta.com",
    price: 289.1,
    changesPercentage: "+1.40%",
  },
  NVDA: {
    symbol: "NVDA",
    companyName: "Nvidia Corporation",
    description: "Nvidia makes GPUs...",
    website: "https://www.nvidia.com",
    image: "https://logo.clearbit.com/nvidia.com",
    price: 437.3,
    changesPercentage: "+2.55%",
  },
  NFLX: {
    symbol: "NFLX",
    companyName: "Netflix Inc.",
    description: "Netflix streams video content...",
    website: "https://www.netflix.com",
    image: "https://logo.clearbit.com/netflix.com",
    price: 395.8,
    changesPercentage: "-1.15%",
  },
  INTC: {
    symbol: "INTC",
    companyName: "Intel Corporation",
    description: "Intel manufactures semiconductors...",
    website: "https://www.intel.com",
    image: "https://logo.clearbit.com/intel.com",
    price: 48.12,
    changesPercentage: "-0.65%",
  },
  ADBE: {
    symbol: "ADBE",
    companyName: "Adobe Inc.",
    description: "Adobe develops creative software...",
    website: "https://www.adobe.com",
    image: "https://logo.clearbit.com/adobe.com",
    price: 610.4,
    changesPercentage: "+3.15%",
  },
  ZM: {
    symbol: "ZM",
    companyName: "Zoom Video Communications",
    description: "Zoom offers video conferencing...",
    website: "https://zoom.us",
    image: "https://logo.clearbit.com/zoom.us",
    price: 69.5,
    changesPercentage: "-0.35%",
  },
  PYPL: {
    symbol: "PYPL",
    companyName: "PayPal Holdings Inc.",
    description: "PayPal offers digital payment services...",
    website: "https://www.paypal.com",
    image: "https://logo.clearbit.com/paypal.com",
    price: 67.8,
    changesPercentage: "+1.95%",
  },
  CRM: {
    symbol: "CRM",
    companyName: "Salesforce.com Inc.",
    description: "CRM cloud-based software...",
    website: "https://www.salesforce.com",
    image: "https://logo.clearbit.com/salesforce.com",
    price: 229.2,
    changesPercentage: "-0.75%",
  },
  QCOM: {
    symbol: "QCOM",
    companyName: "Qualcomm Inc.",
    description: "Qualcomm develops wireless technology...",
    website: "https://www.qualcomm.com",
    image: "https://logo.clearbit.com/qualcomm.com",
    price: 121.7,
    changesPercentage: "+0.55%",
  },
  AVGO: {
    symbol: "AVGO",
    companyName: "Broadcom Inc.",
    description: "Broadcom designs and develops semiconductors...",
    website: "https://www.broadcom.com",
    image: "https://logo.clearbit.com/broadcom.com",
    price: 890.3,
    changesPercentage: "+2.30%",
  },
  CSCO: {
    symbol: "CSCO",
    companyName: "Cisco Systems Inc.",
    description: "Cisco builds networking solutions...",
    website: "https://www.cisco.com",
    image: "https://logo.clearbit.com/cisco.com",
    price: 55.1,
    changesPercentage: "-0.40%",
  },
  UBER: {
    symbol: "UBER",
    companyName: "Uber Technologies Inc.",
    description: "Uber offers ride-sharing services...",
    website: "https://www.uber.com",
    image: "https://logo.clearbit.com/uber.com",
    price: 47.6,
    changesPercentage: "+1.20%",
  },
  SHOP: {
    symbol: "SHOP",
    companyName: "Shopify Inc.",
    description: "Shopify provides e-commerce platform...",
    website: "https://www.shopify.com",
    image: "https://logo.clearbit.com/shopify.com",
    price: 73.4,
    changesPercentage: "+0.95%",
  },
  SPOT: {
    symbol: "SPOT",
    companyName: "Spotify Technology S.A.",
    description: "Spotify offers music streaming...",
    website: "https://www.spotify.com",
    image: "https://logo.clearbit.com/spotify.com",
    price: 152.9,
    changesPercentage: "-1.05%",
  },
  SQ: {
    symbol: "SQ",
    companyName: "Block Inc",
    description: "Block offers financial services and payments...",
    website: "https://www.block.xyz",
    image: "https://logo.clearbit.com/block.xyz",
    price: 68.7,
    changesPercentage: "+0.75%",
  },
};

export const mockHistorical = {
  AAPL: {
    historical: [
      { date: "2024-07-01", close: 185.5 },
      { date: "2024-07-02", close: 186.2 },
      { date: "2024-07-03", close: 187.9 },
      { date: "2024-07-04", close: 189.3 },
      { date: "2024-07-05", close: 191.0 },
      { date: "2024-07-06", close: 193.4 },
      { date: "2024-07-07", close: 195.2 },
      { date: "2024-07-08", close: 196.9 },
      { date: "2024-07-09", close: 198.23 },
    ],
  },
  TSLA: {
    historical: [
      { date: "2024-07-01", close: 650.5 },
      { date: "2024-07-02", close: 658.9 },
      { date: "2024-07-03", close: 670.1 },
      { date: "2024-07-04", close: 680.4 },
      { date: "2024-07-05", close: 689.3 },
      { date: "2024-07-06", close: 695.2 },
      { date: "2024-07-07", close: 698.8 },
      { date: "2024-07-08", close: 700.9 },
      { date: "2024-07-09", close: 701.32 },
    ],
  },
  AMZN: {
    historical: [
      { date: "2024-07-01", close: 126.2 },
      { date: "2024-07-02", close: 127.0 },
      { date: "2024-07-03", close: 128.4 },
      { date: "2024-07-04", close: 130.3 },
      { date: "2024-07-05", close: 132.1 },
      { date: "2024-07-06", close: 133.9 },
      { date: "2024-07-07", close: 132.8 },
      { date: "2024-07-08", close: 132.4 },
      { date: "2024-07-09", close: 132.5 },
    ],
  },
};
